### ISSUE TITLE
No way to open Cycles/Node Graph Editor from 3ds Max

### ISSUE THREAD

**Issue by theawesomecoder61** [jlwitthuhn/cycles-shader-editor#1]
There does not seem to be a way to open the Node Graph Editor window from 3ds Max.

**Comment by jlwitthuhn** [comment]
Do you see the "Cycles Shader Graph - 08" and "Cycles Shader Graph -16" materials in your Max material editor? They will only appear if your renderer is set to either Cycles or Scanline.

If you do, make one of those and then click the "Open Node Graph Editor" button in the parameter rollout and the editor window should pop up.

If either you don't have those materials available or the button doesn't work, let me know and I can look into this further.
